name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller
          if [ ${{ matrix.os }} == 'macos-latest' ]; then
            pip install py2app
          fi

      - name: Build executable
        run: |
          if [ ${{ matrix.os }} == 'macos-latest' ]; then
            python setup.py py2app
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            pyinstaller --onefile --windowed --icon=assets/icon.ico DB_script.py
          else
            pyinstaller --onefile --windowed DB_script.py
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: dist/
