name: Build and Package

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install specific version of PyInstaller
      run: pip install pyinstaller==6.10.0
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl pandas xlsxwriter sv-ttk
        
    - name: Build executable
      run: |
        pyinstaller DB_script.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DB_script
        path: dist/
