name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            pip install py2app
            pip install --use-pep517 wheel
          fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller

      - name: Build executable (macOS)
        if: runner.os == 'macOS'
        run: python setup.py py2app

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --windowed --icon=assets/icon.ico DB_script.py

      - name: Build executable (Linux)
        if: runner.os == 'Linux'
        run: pyinstaller --onefile --windowed DB_script.py

      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: executable-linux
          path: dist/

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: executable-windows
          path: dist/

      - name: Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: executable-macos
          path: dist/
